# Hyprland terminal screensaver
env = PATH,$HOME/.local/bin:$PATH

bind = SUPER, F12, exec, /home/xue/.local/bin/dakhilsaver

windowrule = fullscreen on, match:class ^(org\.hypr_tty_dakhilsaver)
windowrule = float on, match:class ^(org\.hypr_tty_dakhilsaver)
windowrule = animation slide, match:class ^(org\.hypr_tty_dakhilsaver)
